apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-server
  namespace: yolo
  labels:
    app: yolo-server
spec:
  selector:
    matchLabels:
      app: yolo-server
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: yolo-server
    spec:
      automountServiceAccountToken: false
      containers:
        - name: yolo-server
          image: blindx604/yolo-server:1.1.5
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health-check
              port: 5000
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password

            - name: MONGODB_URI
              # reference username and password to create uri
              # value: mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongodb-service:27017/
              value: mongodb://mongodb-service:27017/

          ports:
            - containerPort: 5000
              name: yolo-server
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: yolo-service
  namespace: yolo
  labels:
    app: yolo-service
spec:
  selector:
    app: yolo-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
