apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client
  labels:
    app: yolo-client
spec:
  selector:
    matchLabels:
      app: yolo-client
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      automountServiceAccountToken: false
      containers:
        - name: yolo-client
          image: blindx604/yolo-client:1.0.3
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 80
              name: yolo-client

          env:
            - name: REACT_APP_API_URL
              value: http://yolo-server:5000

      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: yolo-client
  labels:
    app: yolo-client
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30001
  selector:
    app: yolo-client
  type: LoadBalancer
