apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client
  namespace: yolo
  labels:
    app: yolo-client
spec:
  selector:
    matchLabels:
      app: yolo-client
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      automountServiceAccountToken: false
      containers:
        - name: yolo-client
          image: blindx604/yolo-client:1.1.2
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 3000
              name: yolo-client
          env:
            - name: REACT_APP_API_URL
              value: http://yolo-service:5000

      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: yolo-client
  namespace: yolo
  labels:
    app: yolo-client
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 30000
  selector:
    app: yolo-client
  type: LoadBalancer
