services:
  server:
    image: blindx604/yolo-server:1.1.5
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
    networks:
      - yolo-network
    restart: always
  client:
    image: blindx604/yolo-client:1.0.10
    networks:
      - yolo-network
    environment:
      - REACT_APP_API_URL=http://server:5000
    ports:
      - '80:80'
    depends_on:
      - server
    restart: always
  mongodb:
    image: mongo
    volumes:
      - ./mongo-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - yolo-network

networks:
  yolo-network:
    driver: bridge
