---
- name: Execute Terraform
  hosts: localhost
  vars:
    terraform_dir: ./Stage_two/terraform

  tasks:
    - name: Initialize Terraform
      shell: terraform init
      args:
        chdir: "{{ terraform_dir }}"

    - name: Apply Terraform
      shell: terraform apply -auto-approve
      args:
        chdir: "{{ terraform_dir }}"


- import_playbook: playbook.yml
