---
- name: Provisioning webservers
  hosts: all
  gather_facts: false
  become: yes
  vars:
    repo_url: https://github.com/Ebenezr/yolo.git
    user: ubuntu
    dest: /home/{{ user }}/yolo

  tasks:
    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ dest }}"
        update: yes
        force: yes
        clone: yes
        accept_hostkey: yes
        recursive: yes
        version: master

    - name: install pip3
      apt:
        name: python3-pip
        state: present

    - name: Install Docker
      become: yes
      pip:
        name: docker==6.1.3
        state: present

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present

    - name: Run Docker Compose
      community.docker.docker_compose:
        project_src: "{{ dest }}"
        files:
          - docker-compose.yml
