name: Docker Continuous Integration

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Client version
      id: package-version-client
      run: echo "::set-output name=version::$(jq -r .version ./client/package.json)"

    - name: Get Server version
      id: package-version-server
      run: echo "::set-output name=version::$(jq -r .version ./backend/package.json)"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Backend Image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/yolo-server:${{ steps.package-version-server.outputs.content }}

    - name: Build and push Client Image
      uses: docker/build-push-action@v4
      with:
        context: ./client
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/yolo-client:${{ steps.package-version-client.outputs.content }}

    - name: Push Backend Image
      uses: docker/build-push-action@v4
      with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          push: true


    - name: Push Client Image
      uses: docker/build-push-action@v4
      with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          push: true
